version: '3'
services:
  semawi:
    build:
      context: .
      dockerfile: Dockerfile
    image: semawi:2018_01
    ports:
      - "80:80"
    volumes:
      - /srv/semawi/LocalSettings.php:/var/www/wiki/LocalSettings.php
      - /srv/semawi/php.ini:/etc/php5/apache2/php.ini
      - /srv/semawi/images/:/var/www/wiki/images/
      - /srv/semawi/nanlogo.png:/var/www/wiki/resources/assets/nanlogo.png
      - /srv/semawi/gc2smw.cfg:/opt/gc2/gc2smw.cfg
      - /srv/semawi/freetds.conf:/etc/freetds/freetds.conf
      - /srv/semawi/odbcinst.ini:/etc/odbcinst.ini
      - /srv/semawi/odbc.ini:/etc/odbc.ini
    networks:
      - wiki_network
    container_name: semawi-mediawiki
    restart: on-failure
    depends_on:
      - wikidb
    hostname: semawi-mediawiki
  wikidb:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wiki
      MYSQL_USER: wiki
      MYSQL_PASSWORD: wiki
    networks:
      - wiki_network
    container_name: semawi-mysql
    hostname: semawi-mysql
    restart: on-failure

networks:
  wiki_network:
    driver: bridge
